src/stores/calculatorStore.js
src/stores/counterStore.js

- option 방식의 store 예제를 setup방식으로 변경
---

[refactor] counterStore, CalculatorStore를 setup방식으로 수정

---

src/components/common/Calendar.vue

close #36 
달력 디자인 개
---
25-05-29 / 25-05-30 안에 데이터도 포함되어 있습니다.

[refactor] 달력 디자인 개선

---

src/App.vue
src/apis/apiClient.js
src/apis/routes/auth.js
src/apis/routes/index.js
src/components/common/MainSidebar.vue
src/dto/LoginRequestDTO.js
src/dto/LoginResponseDTO.js
src/router/index.js
src/services/authService.js
src/stores/authStore.js
src/views/DashboardPage.vue
src/views/login/LoginPage.vue

close #38
close #40
---
- 로그인 상태 유지X
- dto 디렉토리 추가
- env 적용
- http://localhost:8080/login

[feat] login

---

src/apis/routes/mail.js
src/dto/employment/mail/interviewMailResponseDTO.js
src/dto/employment/mail/jobtestMailResponseDTO.js
src/dto/employment/mail/mailResponseDTO.js
src/dto/employment/mail/mailTemplateResponseDTO.js
src/services/mailService.js
src/services/mailTemplateService.js
src/stores/mailTemplateStore.js

#56 
안내 메일 도메인 라우팅 주소 설정 / DTO 생성 / service 생성 / store 생성
---

[refactor] : 안내 메일 도메인 라우팅 주소 설정 / DTO 생성 / service 생성 / store 생성

---

src/components/employment/DescriptiveQuestionForm.vue
src/components/employment/MultipleQuestionForm.vue
src/components/employment/SubjectiveForm.vue
src/dto/employment/jobtest/createGradingCriteriaRequestDTO.js
src/dto/employment/jobtest/createQuestionOptionRequestDTO.js
src/dto/employment/jobtest/createQuestionRequestDTO.js
src/services/jobtestQuestionService.js
src/views/employment/JobtestQuestionCreatePage.vue

close #66
- 실무테스트 문제 등록 페이지 구현
- 백엔드의 #244 PR을 머지하거나 refactor/sh/insert_question 브랜치를 체크아웃하고 테스트해야 정상 작동합니다.
https://github.com/Pive-Guyz/be14-fin-Empick-BE/pull/244
- CSS는 추후 수정할 예정이니 기능 동작만 확인 부탁드립니다.
- 현재 작성자의 정보가 무조건 1번으로 들어가고 있습니다. 추후 수정할 에정입니다.
---
- 선택형 문제 등록
- 단답형 문제 등록
- 서술형 문제 등록
- 필요한 데이터가 입력되지 않았을 때
로그인을 해야만 테스트가 가능합니다.

[feat] 실무테스트 문제 등록 페이지 구현

---

src/views/DashboardPage.vue

!hotfix : 대쉬보드로 페이지 링크 병합

---

src/components/mail/SendMailModal.vue
src/views/test/MJTestMainPage.vue

[feat] 안내 메일 발송 모달 기능 구현

---

src/components/employment/IntroduceResult.vue
src/json/fullMenu.js
src/router/employment.routes.js
src/views/employment/ApplicantPage.vue
src/views/employment/ApplicationPage.vue

[feat] 지원서 상세 정보 페이지 구현

---

src/apis/routes/application.js
src/dto/employment/application/applicantResponseDTO.js
src/dto/employment/application/applicationResponeDTO.js
src/router/employment.routes.js
src/services/applicantService.js
src/services/applicationService.js
src/stores/applicantStore.js
src/stores/applicationStore.js

#46 
지원서 / 지원자 도메인 api / DTO / service / store 구현
---

[feat] 지원서 / 지원자 도메인 api / DTO / service / store 구현

---

eslint.config.js
package-lock.json
package.json

---
- 할것도 많은데 리뷰로 일일히 잡아내고 코멘트 달기 힘듦. (내가 쿠우쿠우 골드를 사야할 확률이 높아짐)
- vue 파일에서 api, axios, service를 import 하여 사용할 시에 에러 발생 (실행은 됨)
- 그럼에도 지켜지지 않았을 경우, npx eslint src/ 명령어로 위의 규칙에 위반되는 코드와 파일을 모두 찾아내서 배포시에 공수를 줄일수 있음.
+ test/ 디렉토리 내에서는 lint 규칙 무시 가능

!hotfix : eslint 적용 (MVVM 패턴 강제)

---

src/components/employment/IntroduceEvaluationInput.vue
src/views/employment/ApplicationPage.vue

[feat] 지원서 컴포넌트 디자인 변경

---

src/components/employment/JobtestQuestionDetailModal.vue
src/views/employment/JobtestQuestionListPage.vue

close #이슈번호
- 문제 상세 보기에 정답인 선택지 표시
---
- 만약 문제에 정답이 선택지에 없다면 정답 표시가 안됩니다. 더미데이터 입력에 유의해주세요.
- 문제 목록에서 항목을 누르면 해당 모달이 보입니다.

[refactor] 문제 상세 보기 - 선택지에 정답 표시

---

src/components/employment/QuestionCreateModal.vue
src/views/employment/JobtestCreatePage.vue
src/views/employment/JobtestQuestionCreatePage.vue

close #이슈번호
- 실무테스트 생성 시 로그인한 회원 id 연동
- 실무테스트 문제 생성 시 로그인한 회원 id 연동
---

[refactor] 문제, 실무테스트 생성자 실제 로그인한 회원 id 연동

---

src/apis/routes/member.js
src/services/memberService.js
src/stores/memberRegisterStore.js
src/stores/memberStore.js
src/views/orgstructure/MemberRegisterPage.vue

- 사원 등록 엔드포인트 수정
- 사원 검색 service 추가
- 다중 사원 등록 기능 / 단일 사원 등록 버튼
---
https://github.com/user-attachments/assets/ce677426-862d-410d-9a66-f284c288ed46

[feat] 지원자 일괄 사원 등록 + 사원 검색 service

---

src/components/common/Header.vue
src/constants/approval/approvalStatus.js
src/dto/employment/recruitment/recruitmentDetailResponseDTO.js
src/services/recruitmentService.js
src/views/approval/ApprovalInboxPage.vue

* 요청받은 결재 목록 페이지에 필터링 추가
* 헤더 드롭다운 위치 조정
- [요청받은 결재 목록 페이지](http://localhost:8080/approval/inbox)

[refactor] 요청받은 결재 목록 페이지 필터링 추가/헤더 드롭다운 위치 조정

---

src/dto/employment/recruitment/recruitmentDetailResponseDTO.js
src/services/recruitmentService.js

recruitmentDetailResponseDTO -> RecruitmentDetailResponseDTO

[refactor] DTO명 수정

---

src/apis/apiClient.js
src/apis/routes/member.js
src/components/attendance/WeekSummaryCard.vue
src/components/common/CircleLoading.vue
src/dto/member/memberSignUpRequestDTO.js
src/services/memberService.js
src/stores/memberRegisterStore.js
src/stores/memberStore.js
src/views/orgstructure/MemberRegisterPage.vue

close #129 
close #71 
- 백엔드의 https://github.com/Pive-Guyz/be14-fin-Empick-BE/pull/309 가 merge 또는 브랜치 변경시에만 동작함
- memberStore와 엃혀 있던 사원 등록 기능 분리
- 지원자 일괄 등록시 개별적으로 프로필 이미지가 유지되지 않고 전역적으로 공유 되는 문제 수정
- components/common에 로딩 컴포넌트 추가 
---

[refactor] 사원 등록 프로필 이미지 업로드 방식 변경

---

src/components/attendance/AttendanceSummaryCard.vue
src/composables/useAttendanceDetail.js
src/composables/useMemberList.js
src/config/attendance/businessRules.js
src/config/attendance/constants.js
src/constants/common/fullMenu.js
src/dto/attendance/attendanceCategoryRequestDTO.js
src/dto/attendance/attendanceRecordCreateRequestDTO.js
src/dto/attendance/attendanceRecordResponseDTO.js
src/stores/attendanceStore.js
src/utils/attendance/attendanceCalculator.js
src/utils/memberUtils.js
src/views/MainPage.vue

[hotfix] 근태, 메뉴 인사 라우팅 수정

---

src/apis/routes/introduce.js
src/components/employment/IntroduceEvaluationInput.vue
src/constants/employment/applicationStatus.js
src/dto/employment/application/applicationResponeDTO.js
src/services/applicationService.js
src/services/introduceService.js
src/services/introduceStandardItemService.js
src/stores/applicationStore.js
src/utils/errorHandler.js
src/views/employment/ApplicantPage.vue
src/views/employment/ApplicationPage.vue
src/views/employment/IntroduceStandardItemManagePage.vue

close #이슈번호
지원서에 자소서 연동 성공  /
자기소개서 평가 결과 등록 연동 성공  /
평가 절차에 등록된 데이터 조회 연동  / 
평가결과서 데이터 상시 조회 연동 / 
전형절차에서도 조회 연동  
---
/employment/applications/{id}
http://localhost:8080/employment/applications/11?applicantId=11&applicationId=4&name=%EA%B3%BD%EC%9A%B0%EC%84%9D&phone=010-3178-3767&email=dntjr123589%40naver.com&profileUrl=&birth=1999-07-18&address=%EC%9E%A5%EC%8A%B9%EB%B0%B0%EA%B8%B0&recruitmentId=1&introduceRatingResultId=&jobId=&jobName=&createdAt=2025-06-22T21%3A32%3A33&status=WAITING&updatedAt=&updatedBy=&from=%2Femployment%2Fapplicant

[feat] 지원서에 자소서 연동 성공  / 자기소개서 평가 결과 등록 연동 성공  / 평가 절차에 등록된 데이터 조회 연동  / 평가결과서 데이터 상시 조회 연동 / 전형절차에서도 조회 연동  

---

src/apis/routes/introduce.js
src/components/employment/IntroduceEvaluationInput.vue
src/constants/employment/applicationStatus.js
src/dto/employment/application/applicationResponeDTO.js
src/services/applicationService.js
src/services/introduceService.js
src/services/introduceStandardItemService.js
src/stores/applicationStore.js
src/utils/errorHandler.js
src/views/employment/ApplicantPage.vue
src/views/employment/ApplicationPage.vue
src/views/employment/IntroduceStandardItemManagePage.vue

close #이슈번호
---
- http://localhost:8080/employment/applications/11?applicantId=11&applicationId=4&name=%EA%B3%BD%EC%9A%B0%EC%84%9D&phone=010-3178-3767&email=dntjr123589%40naver.com&profileUrl=&birth=1999-07-18&address=%EC%9E%A5%EC%8A%B9%EB%B0%B0%EA%B8%B0&recruitmentId=1&introduceRatingResultId=4&jobId=&jobName=&createdAt=2025-06-22T21%3A32%3A33&status=REJECTED&updatedAt=2025-06-23T00%3A18%3A05&updatedBy=&from=%2Femployment%2Fapplicant [테스트항목 1]
- http://localhost:8080/employment/applicant [테스트항목 2]

[feat] 지원서 상태 변경 연동 

---

src/views/career/CareerRecruitmentDetail.vue
src/views/career/CareerRecruitmentList.vue
src/views/career/CareerResumePage.vue
src/views/employment/IntroduceStandardCreatePage.vue
src/views/employment/IntroduceStandardItemManagePage.vue

close #이슈번호
- 기준표 항목 관리 페이지에서 엔터로 추가하기 말고 추가하기 버튼 생성 
- 기준표 목록 페이지에서 취소버튼 없애고 나머지 버튼 위치 수정
- 지원자 사이트 채용공고 목록 페이지 제목 변
- 지원자 사이트 채용공고 상세 페이지에서 제목이 <p>내용<p/>로 나오던 오류 수정
- 이력서/자소서 등록페이지 입력 칸 키우기, 줄바꿈 추가, 자소서 템플릿 제목 삭제 
---
---
---
---
---
- [기준표항목페이지](http://localhost:8080/employment/introduce-standard-items/manage)
- [기준표페이지](http://localhost:8080/employment/introduce-standard/create)
- [지원자 사이트 채용 공고 목록 페이지](http://localhost:8080/career/recruitments/)
- [지원자 사이트 채용 공고 상세 페이지](http://localhost:8080/career/recruitments/2)
- [지원자 사이트 이력서/자소서 작성 페이지](http://localhost:8080/career/recruitments/resume/2?applicantId=13&applicationId=6)

[ref] 페이지 디자인 수정 

---

src/apis/routes/file.js
src/services/fileService.js
src/services/introduceService.js
src/views/career/ApplicantRegisterPage.vue
src/views/career/CareerRecruitmentDetail.vue
src/views/career/CareerRecruitmentList.vue
src/views/career/CareerResumePage.vue
src/views/employment/ApplicationPage.vue
src/views/employment/IntroduceStandardCreatePage.vue
src/views/employment/IntroduceStandardItemManagePage.vue

feat: s3 프로필 사진

---

src/views/employment/ApplicationPage.vue
src/views/login/LoginPage.vue

#163 
지원서 상세 페이지 면접 점수 조회 기능 구현
---

[feat] 지원서 상세 페이지 면접 점수 조회 기능 구현

---

src/components/common/InterviewScheduleCalendar.vue
src/views/employment/CreateInterviewSheetPage.vue
src/views/employment/InterviewSchedulePage.vue
src/views/employment/InterviewSheetPage.vue

#77 
#87 
면접 일정 페이지 디자인 개선
면접 평가표 페이지 디자인 개선
---

[refactor] 면접 일정 페이지 디자인 개선 / 면접 평가표 페이지 디자인 개선

---

src/views/employment/SendEmailPage.vue

[refactor] 안내 메일 발송 페이지 디자인 개선

---

src/App.vue
src/apis/apiClient.js
src/services/authService.js
src/stores/authStore.js
src/utils/errorHandler.js
src/views/MainPage.vue

---
https://github.com/user-attachments/assets/f24b10a2-4c52-463a-bc81-19f65d112edd

!hotfix : 로그아웃 무한 루프

---

src/router/employment.routes.js
src/views/employment/ApplicantPage.vue
src/views/employment/ApplicationPage.vue
src/views/employment/SendEmailPage.vue

[refactor] 안내 메일 발송 화면 재구성

---

src/views/employment/JobtestCreatePage.vue
src/views/employment/JobtestDetailPage.vue

close #이슈번호
- 실무테스트 수정 시 문제도 할당할 수 있게 수정 
- 할당된 지원자가 있으면 오류나게 수정
- 문제 등록/수정 시 0점으로 할당하는 경우엔 에러뜨게
---

[refactor] 실무테스트 수정 구현

---

src/stores/memberStore.js
src/views/employment/InterviewDetailPage.vue

[refactor] 면접관 이름 표시

---

src/views/employment/ApplicantPage.vue

close #이슈번호
지원자 목록 페이지 필터링 기능 추가
---
- [http://localhost:8080/employment/applicant](http://localhost:8080/employment/applicant)

[feat] 지원자 목록 페이지 필터링 기능 추가

---

src/views/employment/ApplicantRecruitmentPage.vue
src/views/employment/ApplicationItemSelectPage.vue

* 채용공고 등록/수정 시 지원서 항목 필수여부 반영 오류 수정
* 채용공고별 지원자 처리 상태 수정
* [채용공고 등록 페이지](http://localhost:8080/employment/recruitments/create)
* [채용공고별 지원자 페이지](http://localhost:8080/employment/applicant/recruitments/1)

[refactor] 채용공고 등록 시 지원서 항목 필수여부 반영 오류 수정 / 채용공고별 지원자 처리 상태 수정

---

src/components/employment/InterviewEvaluationCriteria.vue
src/components/employment/InterviewSheetModal.vue
src/stores/interviewStore.js
src/views/employment/CreateInterviewPage.vue
src/views/employment/InputInterviewScorePage.vue

[refactor] 면접 도메인 페이지 디자인 수정

---

src/views/employment/RecruitmentCreatePage.vue
src/views/employment/RecruitmentDetailPage.vue
src/views/employment/RecruitmentUpdatePage.vue

* 채용공고 프로세스 디자인 변경
- [채용공고 상세 조회 페이지](http://localhost:8080/employment/recruitments/1?page=1)

[refactor] 채용공고 프로세스 디자인 변경

---

src/views/employment/ApplicationPage.vue

[refactor] 지원서 페이지 면접관 이름 표시

---

src/components/employment/IntroduceEvaluationInput.vue
src/stores/applicationStore.js
src/views/career/CareerResumePage.vue
src/views/employment/ApplicationPage.vue
src/views/employment/IntroduceStandardCreatePage.vue
src/views/employment/IntroduceStandardItemManagePage.vue
src/views/employment/IntroduceStandardListPage.vue
src/views/employment/IntroduceTemplateCreatePage.vue
src/views/employment/IntroduceTemplateItemManagePage.vue
src/views/employment/IntroduceTemplateListPage.vue

- 지원서 상태 변경이 db에 쌓이지 않던 버그 해결
- 해당 상태에서 한단계만 변경가능하게 수정 ex) 서류합격에서 면접합격은 불가능 
- 불합격 또는 최종합격 상태에서 상태변경 불가능 
- 불합격으로 상태 변경 시 이전 단계까지 저장되어 하단 카드에 기록 ex) 서류대기중 -> 서류합격 -> 불합격 
- 하단 카드 명칭 다음 단계 -> 진행 상태 로 변경 
- 하단 카드에서 다음 전형 진행 버튼 삭제 
---
---
---

[ref] 지원서 상태 변경 관련 리펙토링 

---

src/components/common/MainSidebar.vue

close #이슈번호
- 사이드바 다크모드 토글 삭제
- 사이드바

[refactor] 사이드바에 다크모드 토글 삭제

---

src/dto/employment/applicant/applicationCommandDTO.js
src/dto/employment/application/applicantResponseDTO.js
src/dto/employment/application/applicationResponeDTO.js
src/services/applicationService.js
src/services/introduceService.js
src/stores/introduceStore.js
src/views/career/CareerResumePage.vue

- 지원서 등록 시 오류 수정
- 취소 버튼 연결 수정 
- 지원서 등록 시 수정 불가 모달 추가
- 자소서 평가 결과표 생성 시 지원서에 id 수정
- 지원서에 등록된 자기소개서 평가 결과서에 대해 새로 생성이 아닌 수정 기능 연동 
---

[bug] 지원서 등록 관련 버그 수정

---

src/views/employment/RecruitmentCreatePage.vue
src/views/employment/RecruitmentListPage.vue

* 채용공고 목록에서 작성 버튼 삭제
* 공고 등록 시 이미지 항목 주석처리
[채용공고 목록 페이지](http://localhost:8080/employment/recruitments)

[refactor] 채용공고 목록에서 작성 버튼 삭제

---

src/views/employment/CreateInterviewPage.vue
src/views/employment/CreateInterviewSheetPage.vue
src/views/employment/InputInterviewScorePage.vue
src/views/employment/InterviewDetailPage.vue
src/views/employment/InterviewSchedulePage.vue
src/views/employment/InterviewSheetPage.vue

[refactor] 알림 창 토스트팝업 형식으로 통일

---

src/components/employment/JobtestQuestionDetailModal.vue
src/components/employment/QuestionCreateModal.vue
src/stores/jobtestDetailStore.js
src/views/employment/ApplicantPage.vue
src/views/employment/JobtestAnswerDetailPage.vue
src/views/employment/JobtestCreatePage.vue
src/views/employment/JobtestDetailPage.vue
src/views/employment/JobtestEnterPage.vue
src/views/employment/JobtestExamPage.vue
src/views/employment/JobtestListPage.vue
src/views/employment/JobtestQuestionFormPage.vue
src/views/employment/JobtestQuestionListPage.vue

close #이슈번호
- 토스트 한번만 나오게
- 모달창 확인 버튼만 나오게
- 문제 등록 시 내용 입력안되어있거나 정답이 없는 경우 토스트 나오게
- 실무테스트 문제 상세보기 모달 버튼 디자인 수정
---

[refactor] 토스트 한번만 나오게 / 모달 확인 버튼만 나오게

---

src/constants/common/fullMenu.js
src/router/index.js
src/router/middleware/auth.guard.js
src/utils/errorHandler.js
src/views/career/ApplicantRegisterPage.vue
src/views/career/CareerRecruitmentDetail.vue
src/views/career/CareerRecruitmentList.vue
src/views/career/CareerResumePage.vue
src/views/career/CareerWelfarePage.vue
src/views/errors/CareerErrorPage.vue
src/views/errors/NotFoundPage.vue

close #이슈번호
- 지원자 사이트에서 잘못된 경로 요청 시 지원자용 에러페이지로 이동
- 사이드바/헤더 지원자 관련 메뉴를 제일 처음으로
---

[feat] 지원자 페이지용 에러페이지 생성 / [design] 지원자 페이지 CSS 수정

---

src/views/employment/CreateInterviewSheetPage.vue

#78 
평가표 생성 memberId 들어가게 기능 리팩토링
---

[refactor] 평가표 생성 memberId 들어가게 기능 리팩토링

---

src/views/employment/IntroduceStandardCreatePage.vue
src/views/employment/IntroduceStandardDetailPage.vue
src/views/employment/IntroduceStandardItemCreatePage.vue
src/views/employment/IntroduceStandardItemManagePage.vue
src/views/employment/IntroduceStandardItemPage.vue
src/views/employment/IntroduceStandardListPage.vue
src/views/employment/IntroduceTemplateCreatePage.vue
src/views/employment/IntroduceTemplateDetailPage.vue
src/views/employment/IntroduceTemplateItemManagePage.vue
src/views/employment/IntroduceTemplateListPage.vue

close #이슈번호
- 자기소개서 템플릿 관련 페이지 CSS 수정
- 자기소개서 평가 관련 페이지 CSS 수정
- 자기소개서 템플릿 생성 페이지에서 항목 선택에 검색 추가 + 내부 스크롤 생기게
- 자기소개서 기준표 생성 페이지에서 항목 선택 시 검색 추가 + 내부 스크롤 생기게
---

[design] 자기소개서 템플릿/평가 관련 페이지 css수정

---

src/dto/employment/jobtest/jobtestRequestDTO.js
src/views/approval/ApprovalCreatePage.vue
src/views/employment/JobtestCreatePage.vue

close #이슈번호
- 결재 안내 메세지 창 alter -> toast로 변경
- 실무테스트 시작/끝 시간 기준 변경

[!hotfix] 실무테스트/결재 버그 수정
